In [12]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

In [13]:
data=pd.read_csv('daily_weather.csv')

In [14]:
data.columns

Index(['number', 'air_pressure_9am', 'air_temp_9am', 'avg_wind_direction_9am',
       'avg_wind_speed_9am', 'max_wind_direction_9am', 'max_wind_speed_9am',
       'rain_accumulation_9am', 'rain_duration_9am', 'relative_humidity_9am',
       'relative_humidity_3pm'],
      dtype='object')

In [15]:
data

,number,air_pressure_9am,air_temp_9am,avg_wind_direction_9am,avg_wind_speed_9am,max_wind_direction_9am,max_wind_speed_9am,rain_accumulation_9am,rain_duration_9am,relative_humidity_9am,relative_humidity_3pm
0,0,918.060000,74.822000,271.100000,2.080354,295.400000,2.863283,0.00,0.0,42.420000,36.160000
1,1,917.347688,71.403843,101.935179,2.443009,140.471548,3.533324,0.00,0.0,24.328697,19.426597
2,2,923.040000,60.638000,51.000000,17.067852,63.700000,22.100967,0.00,20.0,8.900000,14.460000
3,3,920.502751,70.138895,198.832133,4.337363,211.203341,5.190045,0.00,0.0,12.189102,12.742547
4,4,921.160000,44.294000,277.800000,1.856660,136.500000,2.863283,8.90,14730.0,92.410000,76.740000
5,5,915.300000,78.404000,182.800000,9.932014,189.000000,10.983375,0.02,170.0,35.130000,33.930000
6,6,915.598868,70.043304,177.875407,3.745587,186.606696,4.589632,0.00,0.0,10.657422,21.385657
7,7,918.070000,51.710000,242.400000,2.527742,271.600000,3.646212,0.00,0.0,80.470000,74.920000
8,8,920.080000,80.582000,40.700000,4.518619,63.000000,5.883152,0.00,0.0,29.580000,24.030000
9,9,915.010000,47.498000,163.100000,4.943637,195.900000,6.576604,0.00,0.0,88.600000,68.050000
10,10,919.650000,77.036000,70.600000,3.825167,85.500000,4.764682,0.00,0.0,22.070000,32.130000
11,11,915.640000,45.716000,241.600000,5.860783,265.800000,8.030615,0.55,1770.0,90.560000,79.090000
12,12,917.390000,49.784000,204.100000,1.275056,211.800000,2.013246,0.00,0.0,73.150000,58.430000
13,13,920.820000,62.438000,213.600000,2.617220,165.700000,3.310671,0.00,0.0,43.640000,27.990000
14,14,911.000000,86.432000,202.900000,1.207948,162.900000,1.677705,0.00,0.0,15.190000,24.370000
15,15,922.383131,70.865263,36.174175,1.847278,58.428632,2.529142,0.00,0.0,12.110889,14.801706
16,16,917.890000,NaN,169.200000,2.192201,196.800000,2.930391,0.00,0.0,48.990000,51.190000
17,17,916.915255,77.018961,234.539345,2.274725,229.474199,2.906513,0.00,0.0,21.031462,20.755683
18,18,918.800000,67.082000,176.100000,4.876529,183.400000,5.569981,0.00,0.0,18.900000,45.870000
19,19,922.040000,68.576000,58.300000,9.551734,81.900000,12.571603,0.00,0.0,7.540000,7.740000
20,20,919.992262,62.964383,54.799094,12.680436,74.254223,15.452306,0.00,0.0,18.809518,14.649909
21,21,917.230000,67.676000,177.800000,2.460634,93.200000,3.288302,0.00,0.0,40.640000,41.340000
22,22,921.125626,68.818772,71.799092,2.576538,95.472334,3.487444,0.00,0.0,11.742201,17.281161
23,23,920.350000,47.570000,192.100000,6.263432,205.700000,7.605596,0.00,0.0,54.550000,66.000000
24,24,921.788229,71.659572,217.405520,1.946447,253.758003,2.719712,0.00,0.0,11.194250,16.331716
25,25,918.030000,50.666000,128.900000,2.527742,117.400000,4.004123,0.00,0.0,76.880000,47.030000
26,26,914.490000,49.892000,163.000000,4.854160,189.600000,6.733189,0.00,0.0,92.100000,90.990000
27,27,914.900000,78.620000,203.300000,1.811921,240.000000,2.751436,0.00,220.0,47.890000,43.900000
28,28,915.840000,40.118000,171.900000,10.535987,188.000000,12.929513,0.00,0.0,86.430000,84.390000
29,29,916.310000,45.428000,183.100000,8.343786,194.600000,10.088599,0.00,0.0,86.150000,90.580000
...,...,...,...,...,...,...,...,...,...,...,...
1065,1065,915.600000,69.584000,185.500000,4.630466,198.200000,5.480503,0.00,0.0,28.970000,39.370000
1066,1066,919.564869,73.726732,68.704694,3.551777,102.571616,4.861315,NaN,0.0,11.657314,17.331823
1067,1067,917.690000,64.994000,178.300000,2.975130,193.900000,3.735690,0.00,0.0,54.880000,52.070000
1068,1068,920.330000,68.864000,122.400000,2.035615,182.000000,3.086977,0.00,0.0,52.380000,62.620000
1069,1069,918.260000,82.220000,186.600000,1.096101,221.500000,1.722444,0.00,0.0,32.460000,56.930000
1070,1070,911.600000,46.346000,110.200000,2.304048,96.100000,3.154085,0.00,0.0,90.510000,62.490000
1071,1071,919.200000,70.250000,156.700000,2.013246,172.300000,2.617220,0.00,0.0,42.060000,41.850000
1072,1072,923.100000,75.596000,178.300000,1.409272,205.200000,1.856660,0.00,0.0,11.880000,19.810000
1073,1073,917.920000,84.650000,30.000000,4.831790,40.100000,5.838413,0.00,0.0,16.220000,27.450000
1074,1074,913.870000,66.938000,171.900000,6.509495,182.300000,7.471380,0.00,0.0,57.430000,53.380000
1075,1075,922.858110,64.989361,63.483047,10.261187,73.170504,11.949206,0.00,0.0,14.525109,15.511157
1076,1076,925.550000,50.918000,32.600000,5.413395,57.500000,8.120092,0.00,10.0,29.090000,23.720000
1077,1077,920.130000,73.292000,193.600000,4.115970,211.300000,4.966007,0.00,0.0,33.520000,38.120000
1078,1078,924.017856,68.370307,56.304083,15.162800,76.585117,19.803578,0.00,0.0,11.599240,9.373013
1079,1079,917.200000,65.264000,137.600000,1.767183,176.700000,2.550112,0.00,0.0,58.370000,65.590000
1080,1080,916.260000,79.772000,185.700000,3.511996,201.500000,4.160708,0.00,0.0,27.680000,20.400000
1081,1081,920.856913,69.884338,47.335966,12.238670,66.729162,16.067860,0.00,0.0,11.956852,12.696233
1082,1082,916.130000,50.108000,211.400000,2.550112,231.800000,3.534365,0.00,0.0,89.800000,53.860000
1083,1083,916.320000,48.308000,46.900000,4.854160,61.700000,5.860783,0.00,0.0,91.030000,62.400000
1084,1084,917.130000,80.240000,183.300000,1.632966,38.500000,2.259309,0.00,0.0,28.260000,34.690000
1085,1085,914.840000,47.354000,190.900000,3.713320,204.400000,4.652835,0.00,0.0,92.300000,88.160000
1086,1086,921.260000,52.646000,261.900000,2.035615,260.500000,3.042238,0.00,0.0,91.110000,81.890000
1087,1087,914.000000,66.650000,173.800000,8.366156,181.000000,9.439887,0.00,0.0,30.920000,47.340000
1088,1088,912.900000,71.870000,129.200000,1.431642,160.000000,2.057985,0.00,0.0,51.840000,55.490000
1089,1089,915.000000,55.040000,191.800000,5.368656,220.900000,7.068730,0.00,0.0,73.550000,69.670000
1090,1090,918.900000,63.104000,192.900000,3.869906,207.300000,5.212070,0.00,0.0,26.020000,38.180000
1091,1091,918.710000,49.568000,241.600000,1.811921,227.400000,2.371156,0.00,0.0,90.350000,73.340000
1092,1092,916.600000,71.096000,189.300000,3.064608,200.800000,3.892276,0.00,0.0,45.590000,52.310000
1093,1093,912.600000,58.406000,172.700000,3.825167,189.100000,4.764682,0.00,0.0,64.840000,58.280000
1094,1094,921.530000,77.702000,97.100000,3.265932,125.900000,4.451511,0.00,0.0,14.560000,15.100000

In [16]:
data.head()

,number,air_pressure_9am,air_temp_9am,avg_wind_direction_9am,avg_wind_speed_9am,max_wind_direction_9am,max_wind_speed_9am,rain_accumulation_9am,rain_duration_9am,relative_humidity_9am,relative_humidity_3pm
0,0,918.060000,74.822000,271.100000,2.080354,295.400000,2.863283,0.0,0.0,42.420000,36.160000
1,1,917.347688,71.403843,101.935179,2.443009,140.471548,3.533324,0.0,0.0,24.328697,19.426597
2,2,923.040000,60.638000,51.000000,17.067852,63.700000,22.100967,0.0,20.0,8.900000,14.460000
3,3,920.502751,70.138895,198.832133,4.337363,211.203341,5.190045,0.0,0.0,12.189102,12.742547
4,4,921.160000,44.294000,277.800000,1.856660,136.500000,2.863283,8.9,14730.0,92.410000,76.740000

In [17]:
data=data.dropna()
data

,number,air_pressure_9am,air_temp_9am,avg_wind_direction_9am,avg_wind_speed_9am,max_wind_direction_9am,max_wind_speed_9am,rain_accumulation_9am,rain_duration_9am,relative_humidity_9am,relative_humidity_3pm
0,0,918.060000,74.822000,271.100000,2.080354,295.400000,2.863283,0.00,0.0,42.420000,36.160000
1,1,917.347688,71.403843,101.935179,2.443009,140.471548,3.533324,0.00,0.0,24.328697,19.426597
2,2,923.040000,60.638000,51.000000,17.067852,63.700000,22.100967,0.00,20.0,8.900000,14.460000
3,3,920.502751,70.138895,198.832133,4.337363,211.203341,5.190045,0.00,0.0,12.189102,12.742547
4,4,921.160000,44.294000,277.800000,1.856660,136.500000,2.863283,8.90,14730.0,92.410000,76.740000
5,5,915.300000,78.404000,182.800000,9.932014,189.000000,10.983375,0.02,170.0,35.130000,33.930000
6,6,915.598868,70.043304,177.875407,3.745587,186.606696,4.589632,0.00,0.0,10.657422,21.385657
7,7,918.070000,51.710000,242.400000,2.527742,271.600000,3.646212,0.00,0.0,80.470000,74.920000
8,8,920.080000,80.582000,40.700000,4.518619,63.000000,5.883152,0.00,0.0,29.580000,24.030000
9,9,915.010000,47.498000,163.100000,4.943637,195.900000,6.576604,0.00,0.0,88.600000,68.050000
10,10,919.650000,77.036000,70.600000,3.825167,85.500000,4.764682,0.00,0.0,22.070000,32.130000
11,11,915.640000,45.716000,241.600000,5.860783,265.800000,8.030615,0.55,1770.0,90.560000,79.090000
12,12,917.390000,49.784000,204.100000,1.275056,211.800000,2.013246,0.00,0.0,73.150000,58.430000
13,13,920.820000,62.438000,213.600000,2.617220,165.700000,3.310671,0.00,0.0,43.640000,27.990000
14,14,911.000000,86.432000,202.900000,1.207948,162.900000,1.677705,0.00,0.0,15.190000,24.370000
15,15,922.383131,70.865263,36.174175,1.847278,58.428632,2.529142,0.00,0.0,12.110889,14.801706
17,17,916.915255,77.018961,234.539345,2.274725,229.474199,2.906513,0.00,0.0,21.031462,20.755683
18,18,918.800000,67.082000,176.100000,4.876529,183.400000,5.569981,0.00,0.0,18.900000,45.870000
19,19,922.040000,68.576000,58.300000,9.551734,81.900000,12.571603,0.00,0.0,7.540000,7.740000
20,20,919.992262,62.964383,54.799094,12.680436,74.254223,15.452306,0.00,0.0,18.809518,14.649909
21,21,917.230000,67.676000,177.800000,2.460634,93.200000,3.288302,0.00,0.0,40.640000,41.340000
22,22,921.125626,68.818772,71.799092,2.576538,95.472334,3.487444,0.00,0.0,11.742201,17.281161
23,23,920.350000,47.570000,192.100000,6.263432,205.700000,7.605596,0.00,0.0,54.550000,66.000000
24,24,921.788229,71.659572,217.405520,1.946447,253.758003,2.719712,0.00,0.0,11.194250,16.331716
25,25,918.030000,50.666000,128.900000,2.527742,117.400000,4.004123,0.00,0.0,76.880000,47.030000
26,26,914.490000,49.892000,163.000000,4.854160,189.600000,6.733189,0.00,0.0,92.100000,90.990000
27,27,914.900000,78.620000,203.300000,1.811921,240.000000,2.751436,0.00,220.0,47.890000,43.900000
28,28,915.840000,40.118000,171.900000,10.535987,188.000000,12.929513,0.00,0.0,86.430000,84.390000
29,29,916.310000,45.428000,183.100000,8.343786,194.600000,10.088599,0.00,0.0,86.150000,90.580000
30,30,919.350000,91.112000,96.400000,2.527742,96.300000,3.377779,0.00,0.0,25.620000,35.690000
...,...,...,...,...,...,...,...,...,...,...,...
1064,1064,913.850000,79.736000,191.700000,3.109347,207.800000,3.981753,0.00,0.0,21.480000,33.190000
1065,1065,915.600000,69.584000,185.500000,4.630466,198.200000,5.480503,0.00,0.0,28.970000,39.370000
1067,1067,917.690000,64.994000,178.300000,2.975130,193.900000,3.735690,0.00,0.0,54.880000,52.070000
1068,1068,920.330000,68.864000,122.400000,2.035615,182.000000,3.086977,0.00,0.0,52.380000,62.620000
1069,1069,918.260000,82.220000,186.600000,1.096101,221.500000,1.722444,0.00,0.0,32.460000,56.930000
1070,1070,911.600000,46.346000,110.200000,2.304048,96.100000,3.154085,0.00,0.0,90.510000,62.490000
1071,1071,919.200000,70.250000,156.700000,2.013246,172.300000,2.617220,0.00,0.0,42.060000,41.850000
1072,1072,923.100000,75.596000,178.300000,1.409272,205.200000,1.856660,0.00,0.0,11.880000,19.810000
1073,1073,917.920000,84.650000,30.000000,4.831790,40.100000,5.838413,0.00,0.0,16.220000,27.450000
1074,1074,913.870000,66.938000,171.900000,6.509495,182.300000,7.471380,0.00,0.0,57.430000,53.380000
1075,1075,922.858110,64.989361,63.483047,10.261187,73.170504,11.949206,0.00,0.0,14.525109,15.511157
1076,1076,925.550000,50.918000,32.600000,5.413395,57.500000,8.120092,0.00,10.0,29.090000,23.720000
1077,1077,920.130000,73.292000,193.600000,4.115970,211.300000,4.966007,0.00,0.0,33.520000,38.120000
1078,1078,924.017856,68.370307,56.304083,15.162800,76.585117,19.803578,0.00,0.0,11.599240,9.373013
1079,1079,917.200000,65.264000,137.600000,1.767183,176.700000,2.550112,0.00,0.0,58.370000,65.590000
1080,1080,916.260000,79.772000,185.700000,3.511996,201.500000,4.160708,0.00,0.0,27.680000,20.400000
1081,1081,920.856913,69.884338,47.335966,12.238670,66.729162,16.067860,0.00,0.0,11.956852,12.696233
1082,1082,916.130000,50.108000,211.400000,2.550112,231.800000,3.534365,0.00,0.0,89.800000,53.860000
1083,1083,916.320000,48.308000,46.900000,4.854160,61.700000,5.860783,0.00,0.0,91.030000,62.400000
1084,1084,917.130000,80.240000,183.300000,1.632966,38.500000,2.259309,0.00,0.0,28.260000,34.690000
1085,1085,914.840000,47.354000,190.900000,3.713320,204.400000,4.652835,0.00,0.0,92.300000,88.160000
1086,1086,921.260000,52.646000,261.900000,2.035615,260.500000,3.042238,0.00,0.0,91.110000,81.890000
1087,1087,914.000000,66.650000,173.800000,8.366156,181.000000,9.439887,0.00,0.0,30.920000,47.340000
1088,1088,912.900000,71.870000,129.200000,1.431642,160.000000,2.057985,0.00,0.0,51.840000,55.490000
1089,1089,915.000000,55.040000,191.800000,5.368656,220.900000,7.068730,0.00,0.0,73.550000,69.670000
1090,1090,918.900000,63.104000,192.900000,3.869906,207.300000,5.212070,0.00,0.0,26.020000,38.180000
1091,1091,918.710000,49.568000,241.600000,1.811921,227.400000,2.371156,0.00,0.0,90.350000,73.340000
1092,1092,916.600000,71.096000,189.300000,3.064608,200.800000,3.892276,0.00,0.0,45.590000,52.310000
1093,1093,912.600000,58.406000,172.700000,3.825167,189.100000,4.764682,0.00,0.0,64.840000,58.280000
1094,1094,921.530000,77.702000,97.100000,3.265932,125.900000,4.451511,0.00,0.0,14.560000,15.100000

In [18]:
clean_data=data
clean_data['high_humidity_label']=(clean_data['relative_humidity_3pm']>24.99)*1
clean_data.head()

c:\users\fg\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,number,air_pressure_9am,air_temp_9am,avg_wind_direction_9am,avg_wind_speed_9am,max_wind_direction_9am,max_wind_speed_9am,rain_accumulation_9am,rain_duration_9am,relative_humidity_9am,relative_humidity_3pm,high_humidity_label
0,0,918.060000,74.822000,271.100000,2.080354,295.400000,2.863283,0.0,0.0,42.420000,36.160000,1
1,1,917.347688,71.403843,101.935179,2.443009,140.471548,3.533324,0.0,0.0,24.328697,19.426597,0
2,2,923.040000,60.638000,51.000000,17.067852,63.700000,22.100967,0.0,20.0,8.900000,14.460000,0
3,3,920.502751,70.138895,198.832133,4.337363,211.203341,5.190045,0.0,0.0,12.189102,12.742547,0
4,4,921.160000,44.294000,277.800000,1.856660,136.500000,2.863283,8.9,14730.0,92.410000,76.740000,1

In [19]:
X=clean_data.drop(['relative_humidity_9am','relative_humidity_3pm','high_humidity_label','number'],axis=1)
X.head()

,air_pressure_9am,air_temp_9am,avg_wind_direction_9am,avg_wind_speed_9am,max_wind_direction_9am,max_wind_speed_9am,rain_accumulation_9am,rain_duration_9am
0,918.060000,74.822000,271.100000,2.080354,295.400000,2.863283,0.0,0.0
1,917.347688,71.403843,101.935179,2.443009,140.471548,3.533324,0.0,0.0
2,923.040000,60.638000,51.000000,17.067852,63.700000,22.100967,0.0,20.0
3,920.502751,70.138895,198.832133,4.337363,211.203341,5.190045,0.0,0.0
4,921.160000,44.294000,277.800000,1.856660,136.500000,2.863283,8.9,14730.0

In [20]:
Y=clean_data['high_humidity_label']
Y.head()

0    1
1    0
2    0
3    0
4    1
Name: high_humidity_label, dtype: int32

In [21]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.33)

In [22]:
humidity_clf=DecisionTreeClassifier(max_leaf_nodes=10,random_state=2)
humidity_clf.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=10,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=2,
            splitter='best')

In [23]:
pred_test=humidity_clf.predict(X_test)

In [24]:
from pandas import DataFrame

In [25]:
import numpy as np

In [26]:
pd.concat([DataFrame(np.ravel(Y_test),columns=['Test_data']),DataFrame(pred_test,columns=['predicted_test'])],axis=1)

     Test_data  predicted_test
0            1               1
1            0               1
2            1               0
3            0               0
4            0               0
5            0               1
6            0               0
7            0               0
8            1               1
9            0               0
10           1               0
11           1               1
12           1               1
13           0               0
14           1               1
15           0               0
16           1               1
17           1               1
18           0               0
19           1               1
20           1               1
21           0               1
22           1               1
23           0               1
24           0               0
25           1               1
26           0               0
27           0               1
28           1               0
29           1               1
..         ...             ...
322          0               0
323          1               1
324          0               0
325          1               1
326          0               0
327          0               1
328          1               1
329          0               0
330          0               0
331          1               0
332          0               0
333          1               0
334          0               0
335          0               0
336          1               1
337          0               0
338          1               1
339          0               0
340          1               1
341          1               1
342          1               0
343          0               1
344          0               0
345          0               0
346          0               0
347          0               0
348          1               1
349          1               0
350          0               0
351          1               0

[352 rows x 2 columns]

In [27]:
accuracy_score(Y_test,pred_test)

0.7926136363636364

In [28]:
pred_train=humidity_clf.predict(X_train)
pd.concat([DataFrame(np.ravel(Y_train),columns=['Test_data']),DataFrame(pred_train,columns=['predicted_test'])],axis=1)

     Test_data  predicted_test
0            0               0
1            0               1
2            1               1
3            1               1
4            0               0
5            1               1
6            0               0
7            1               0
8            1               1
9            1               1
10           0               0
11           0               0
12           1               1
13           1               1
14           1               1
15           1               0
16           0               0
17           1               1
18           0               1
19           0               0
20           0               0
21           0               1
22           1               1
23           0               0
24           1               1
25           1               0
26           1               0
27           1               1
28           1               0
29           0               0
..         ...             ...
682          0               0
683          1               1
684          0               1
685          1               1
686          0               0
687          0               1
688          0               0
689          0               0
690          1               0
691          1               1
692          0               0
693          1               1
694          0               0
695          0               1
696          1               0
697          1               1
698          0               0
699          0               0
700          1               1
701          1               1
702          0               0
703          0               0
704          0               0
705          0               0
706          0               0
707          0               0
708          1               1
709          1               0
710          1               0
711          1               1

[712 rows x 2 columns]

In [29]:
accuracy_score(Y_train,pred_train)

0.8314606741573034

In [30]:
humidity_clf=LogisticRegression()
humidity_clf.fit(X_train,Y_train)

c:\users\fg\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [31]:
pred_test=humidity_clf.predict(X_test)
pd.concat([DataFrame(np.ravel(Y_test),columns=['Test_data']),DataFrame(pred_test,columns=['predicted_test'])],axis=1)

     Test_data  predicted_test
0            1               1
1            0               0
2            1               0
3            0               0
4            0               0
5            0               0
6            0               0
7            0               0
8            1               0
9            0               0
10           1               0
11           1               1
12           1               0
13           0               1
14           1               1
15           0               0
16           1               1
17           1               1
18           0               0
19           1               1
20           1               1
21           0               0
22           1               1
23           0               0
24           0               0
25           1               1
26           0               1
27           0               0
28           1               0
29           1               1
..         ...             ...
322          0               0
323          1               1
324          0               0
325          1               1
326          0               0
327          0               0
328          1               1
329          0               0
330          0               1
331          1               1
332          0               0
333          1               1
334          0               0
335          0               0
336          1               1
337          0               1
338          1               1
339          0               0
340          1               0
341          1               1
342          1               1
343          0               1
344          0               0
345          0               0
346          0               1
347          0               0
348          1               0
349          1               0
350          0               0
351          1               0

[352 rows x 2 columns]

In [32]:
accuracy_score(Y_test,pred_test)

0.7443181818181818